[build]
  base = "."
  command = "npm run build"
  functions = "out_functions"
  publish = "out_publish"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-next-dynamic"